pipeline:
  name: allow-failures-case2
stages:
  - build
job-a:
  - stage: build
  - image: alpine:latest
  - failures: true
  - script:
    - exit 1
job-b:
  - stage: build
  - image: alpine:latest
  - needs: [job-a]
  - failures: false
  - script:
    - echo "This runs successfully despite job-a failing."
