pipeline:
  name: allow-failures-case1
stages:
  - build
job-a:
  - stage: build
  - image: alpine
  - failures: false
  - script:
    - exit 1
job-b:
  - stage: build
  - image: alpine
  - needs: [job-a]
  - failures: true
  - script:
    - echo "This should never run because job-a failed and is required."
