pipeline:
  name: allow-failures-case1
stages:
  - build
job-a:
  - stage: build
  - image: alpine
  - script: exit 1
  - failures: false
job-b:
  - stage: build
  - image: alpine
  - script: echo "This should never run because job-a failed and is required."
  - needs: [job-a]
  - failures: true
