pipeline:
  name: allow-failures-case3
stages:
  - test
job-a:
  - stage: test
  - image: alpine
  - script: exit 1
  - failures: true
job-b:
  - stage: test
  - image: alpine
  - script: exit 1
  - needs: [job-a]
  - failures: true
