pipeline:
  name: allow-failures-case3
stages:
  - test
job-a:
  - stage: test
  - image: alpine
  - failures: true
  - script:
    - exit 1
job-b:
  - stage: test
  - image: alpine
  - needs: [job-a]
  - failures: true
  - script:
    - exit 1
