pipeline:
  name: demo-invalid-pipeline
  stages:
    - build
  jobs:
    - name: job-a
      stage: build
      image: alpine
      script:
        - echo "Job A"
      needs: [job-b]  
    - name: job-b
      stage: build
      image: alpine
      script:
        - echo "Job B"
      needs: [job-a]  
